#----------------------------------------------------------------------------
#       Make Workspace
#
# 
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/chajmart/MPC/mwc.pl -type make
#
#----------------------------------------------------------------------------


all: thewordtree

depend: thewordtree-depend

clean generated realclean check-syntax $(CUSTOM_TARGETS):
	@$(MAKE) -f Makefile.thewordtree $(@)

.PHONY: thewordtree
thewordtree:
	@$(MAKE) -f Makefile.thewordtree all

.PHONY: thewordtree-depend
thewordtree-depend:
	@$(MAKE) -f Makefile.thewordtree depend

project_name_list:
	@echo thewordtree
